enum Routes {
    DASHBOARD_SCREEN = 'DASHBOARD_SCREEN',
    PAYMENT_SCREEN = 'PAYMENT_SCREEN',
    SECURE_VALIDATE_SCREEN = 'SECURE_VALIDATE_SCREEN',
    SUCCESS_TRANSFER_SCREEN = 'SUCCESS_TRANSFER_SCREEN',
};

export default Routes;
